version: '3.7'

services:
  api:
    container_name: apid_tango
    image: XXXXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/apid-tango:${APP_DEPLOY_VERSION:-latest}
    mem_limit: 268435456 # 256m
    mem_reservation: 230686720 # 220m
    logging:
      driver: awslogs
      options:
        awslogs-group: apid-tango-$DEPLOY_ENV
        awslogs-region: eu-west-1
    environment: &app_environment
      RAILS_ENV: $DEPLOY_ENV
      RAILS_LOG_TO_STDOUT: 1
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

  app-migration:
    container_name: apid_tango_migration
    image: XXXXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/apid-tango:${APP_DEPLOY_VERSION:-latest}
    command: rails db:migrate db:seed
    environment:
      <<: *app_environment
    labels:
      io.rancher.container.start_once: 'true'
